services:
  - type: web
    name: vendor-pro-2026
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
